// <auto-generated />
using AgendaDistribuidas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AgendaDistribuidas.Migrations
{
    [DbContext(typeof(AgendaDistribuidasContext))]
    [Migration("20181203183403_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaDistribuidas.Models.Contacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Interno");

                    b.Property<string>("Nombre");

                    b.HasKey("ContactoId");

                    b.ToTable("Contacto");
                });
#pragma warning restore 612, 618
        }
    }
}
